// <auto-generated />
using System;
using ERP_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260808092850_AddBranchAndCategoryToProducts")]
    partial class AddBranchAndCategoryToProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AITStudent")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP_System.Models.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<string>("ColorClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActivityLogId");

                    b.ToTable("erp_ActivityLogs", "AITStudent");

                    b.HasData(
                        new
                        {
                            ActivityLogId = 1,
                            ColorClass = "text-primary",
                            CreatedAt = new DateTime(2026, 8, 8, 9, 26, 45, 996, DateTimeKind.Utc).AddTicks(7097),
                            Description = "INV-10045 created",
                            IconClass = "fa-file-invoice",
                            Title = "New Sales Invoice"
                        },
                        new
                        {
                            ActivityLogId = 2,
                            ColorClass = "text-success",
                            CreatedAt = new DateTime(2026, 8, 8, 9, 13, 45, 996, DateTimeKind.Utc).AddTicks(7105),
                            Description = "PO-10023 created",
                            IconClass = "fa-shopping-cart",
                            Title = "New Purchase Order"
                        },
                        new
                        {
                            ActivityLogId = 3,
                            ColorClass = "text-info",
                            CreatedAt = new DateTime(2026, 8, 8, 8, 28, 45, 996, DateTimeKind.Utc).AddTicks(7107),
                            Description = "John Doe added",
                            IconClass = "fa-user-plus",
                            Title = "New Employee Added"
                        },
                        new
                        {
                            ActivityLogId = 4,
                            ColorClass = "text-warning",
                            CreatedAt = new DateTime(2026, 8, 8, 7, 28, 45, 996, DateTimeKind.Utc).AddTicks(7111),
                            Description = "₹25,000 received",
                            IconClass = "fa-hand-holding-usd",
                            Title = "Payment Received"
                        },
                        new
                        {
                            ActivityLogId = 5,
                            ColorClass = "text-danger",
                            CreatedAt = new DateTime(2026, 8, 8, 6, 28, 45, 996, DateTimeKind.Utc).AddTicks(7113),
                            Description = "Product stock updated",
                            IconClass = "fa-boxes",
                            Title = "Stock Updated"
                        });
                });

            modelBuilder.Entity("ERP_System.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GSTNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("BranchId");

                    b.HasIndex("CompanyId");

                    b.ToTable("erp_Branches", "AITStudent");
                });

            modelBuilder.Entity("ERP_System.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CompanyId");

                    b.ToTable("erp_Companies", "AITStudent");
                });

            modelBuilder.Entity("ERP_System.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers", "AITStudent");
                });

            modelBuilder.Entity("ERP_System.Models.Payslip", b =>
                {
                    b.Property<int>("PayslipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayslipId"));

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("HRA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PaidDays")
                        .HasColumnType("int");

                    b.Property<string>("PayPeriod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ProfessionalTax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProvidentFund")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PayslipId");

                    b.HasIndex("UserId");

                    b.ToTable("erp_Payslips", "AITStudent");
                });

            modelBuilder.Entity("ERP_System.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoldQty")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("BranchId");

                    b.ToTable("erp_Products", "AITStudent");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            BranchId = 3,
                            Category = "General",
                            ProductName = "Laptop",
                            Revenue = 450000m,
                            SoldQty = 45,
                            Status = "In Stock",
                            StockQty = 180
                        },
                        new
                        {
                            ProductId = 2,
                            BranchId = 3,
                            Category = "General",
                            ProductName = "Smartphone",
                            Revenue = 340000m,
                            SoldQty = 85,
                            Status = "Low Stock",
                            StockQty = 60
                        },
                        new
                        {
                            ProductId = 3,
                            BranchId = 3,
                            Category = "General",
                            ProductName = "Headphones",
                            Revenue = 180000m,
                            SoldQty = 120,
                            Status = "Out of Stock",
                            StockQty = 40
                        },
                        new
                        {
                            ProductId = 4,
                            BranchId = 3,
                            Category = "General",
                            ProductName = "Keyboard",
                            Revenue = 90000m,
                            SoldQty = 60,
                            Status = "In Stock",
                            StockQty = 100
                        },
                        new
                        {
                            ProductId = 5,
                            BranchId = 3,
                            Category = "General",
                            ProductName = "Mouse",
                            Revenue = 75000m,
                            SoldQty = 75,
                            Status = "In Stock",
                            StockQty = 120
                        });
                });

            modelBuilder.Entity("ERP_System.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("erp_Roles", "AITStudent");
                });

            modelBuilder.Entity("ERP_System.Models.SalaryStructure", b =>
                {
                    b.Property<int>("SalaryStructureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryStructureId"));

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HRA")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("MedicalAllowance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("NetSalary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProfessionalTax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ProvidentFund")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SalaryStructureId");

                    b.HasIndex("UserId");

                    b.ToTable("erp_SalaryStructures", "AITStudent");
                });

            modelBuilder.Entity("ERP_System.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionId");

                    b.ToTable("erp_Transactions", "AITStudent");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 25000m,
                            Date = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "Rahul Enterprises",
                            Status = "Paid",
                            TransactionNo = "INV-10045",
                            Type = "Sales Invoice"
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 18500m,
                            Date = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "Sharma Suppliers",
                            Status = "Pending",
                            TransactionNo = "PO-10023",
                            Type = "Purchase Order"
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 15750m,
                            Date = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "ABC Corporation",
                            Status = "Paid",
                            TransactionNo = "INV-10044",
                            Type = "Sales Invoice"
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 2500m,
                            Date = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "Office Supplies",
                            Status = "Paid",
                            TransactionNo = "EXP-10012",
                            Type = "Expense Entry"
                        },
                        new
                        {
                            TransactionId = 5,
                            Amount = 22000m,
                            Date = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "XYZ Traders",
                            Status = "Pending",
                            TransactionNo = "PO-10022",
                            Type = "Purchase Order"
                        });
                });

            modelBuilder.Entity("ERP_System.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPasswordChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.ToTable("erp_Users", "AITStudent");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BranchId = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 8, 4, 15, 53, 51, 483, DateTimeKind.Unspecified),
                            Email = "admin@erp.com",
                            FailedLoginAttempts = 0,
                            FullName = "Admin User",
                            IsActive = true,
                            IsEmailVerified = false,
                            IsLocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAECozAYaKmaWgP0n3guskgVltZ512o/ZwEe8toCoM41gYTGZsAaDZfFkuqexa4If6tQ==",
                            RoleId = 1,
                            UserCode = "USR001",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("ERP_System.Models.Branch", b =>
                {
                    b.HasOne("ERP_System.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ERP_System.Models.Payslip", b =>
                {
                    b.HasOne("ERP_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP_System.Models.Product", b =>
                {
                    b.HasOne("ERP_System.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("ERP_System.Models.SalaryStructure", b =>
                {
                    b.HasOne("ERP_System.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ERP_System.Models.User", b =>
                {
                    b.HasOne("ERP_System.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ERP_System.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
