// <auto-generated />
using System;
using ERP_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_System.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AITStudent")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERP_System.Models.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<string>("ColorClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ActivityLogId");

                    b.ToTable("erp_ActivityLogs", "AITStudent");

                    b.HasData(
                        new
                        {
                            ActivityLogId = 1,
                            ColorClass = "text-primary",
                            CreatedAt = new DateTime(2026, 8, 5, 12, 24, 53, 217, DateTimeKind.Utc).AddTicks(2107),
                            Description = "INV-10045 created",
                            IconClass = "fa-file-invoice",
                            Title = "New Sales Invoice"
                        },
                        new
                        {
                            ActivityLogId = 2,
                            ColorClass = "text-success",
                            CreatedAt = new DateTime(2026, 8, 5, 12, 11, 53, 217, DateTimeKind.Utc).AddTicks(2113),
                            Description = "PO-10023 created",
                            IconClass = "fa-shopping-cart",
                            Title = "New Purchase Order"
                        },
                        new
                        {
                            ActivityLogId = 3,
                            ColorClass = "text-info",
                            CreatedAt = new DateTime(2026, 8, 5, 11, 26, 53, 217, DateTimeKind.Utc).AddTicks(2116),
                            Description = "John Doe added",
                            IconClass = "fa-user-plus",
                            Title = "New Employee Added"
                        },
                        new
                        {
                            ActivityLogId = 4,
                            ColorClass = "text-warning",
                            CreatedAt = new DateTime(2026, 8, 5, 10, 26, 53, 217, DateTimeKind.Utc).AddTicks(2120),
                            Description = "₹25,000 received",
                            IconClass = "fa-hand-holding-usd",
                            Title = "Payment Received"
                        },
                        new
                        {
                            ActivityLogId = 5,
                            ColorClass = "text-danger",
                            CreatedAt = new DateTime(2026, 8, 5, 9, 26, 53, 217, DateTimeKind.Utc).AddTicks(2123),
                            Description = "Product stock updated",
                            IconClass = "fa-boxes",
                            Title = "Stock Updated"
                        });
                });

            modelBuilder.Entity("ERP_System.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Revenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SoldQty")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQty")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("erp_Products", "AITStudent");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Laptop",
                            Revenue = 450000m,
                            SoldQty = 45,
                            Status = "In Stock",
                            StockQty = 180
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Smartphone",
                            Revenue = 340000m,
                            SoldQty = 85,
                            Status = "Low Stock",
                            StockQty = 60
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Headphones",
                            Revenue = 180000m,
                            SoldQty = 120,
                            Status = "Out of Stock",
                            StockQty = 40
                        },
                        new
                        {
                            ProductId = 4,
                            ProductName = "Keyboard",
                            Revenue = 90000m,
                            SoldQty = 60,
                            Status = "In Stock",
                            StockQty = 100
                        },
                        new
                        {
                            ProductId = 5,
                            ProductName = "Mouse",
                            Revenue = 75000m,
                            SoldQty = 75,
                            Status = "In Stock",
                            StockQty = 120
                        });
                });

            modelBuilder.Entity("ERP_System.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("erp_Roles", "AITStudent");
                });

            modelBuilder.Entity("ERP_System.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TransactionId");

                    b.ToTable("erp_Transactions", "AITStudent");

                    b.HasData(
                        new
                        {
                            TransactionId = 1,
                            Amount = 25000m,
                            Date = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "Rahul Enterprises",
                            Status = "Paid",
                            TransactionNo = "INV-10045",
                            Type = "Sales Invoice"
                        },
                        new
                        {
                            TransactionId = 2,
                            Amount = 18500m,
                            Date = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "Sharma Suppliers",
                            Status = "Pending",
                            TransactionNo = "PO-10023",
                            Type = "Purchase Order"
                        },
                        new
                        {
                            TransactionId = 3,
                            Amount = 15750m,
                            Date = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "ABC Corporation",
                            Status = "Paid",
                            TransactionNo = "INV-10044",
                            Type = "Sales Invoice"
                        },
                        new
                        {
                            TransactionId = 4,
                            Amount = 2500m,
                            Date = new DateTime(2026, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "Office Supplies",
                            Status = "Paid",
                            TransactionNo = "EXP-10012",
                            Type = "Expense Entry"
                        },
                        new
                        {
                            TransactionId = 5,
                            Amount = 22000m,
                            Date = new DateTime(2026, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartyName = "XYZ Traders",
                            Status = "Pending",
                            TransactionNo = "PO-10022",
                            Type = "Purchase Order"
                        });
                });

            modelBuilder.Entity("ERP_System.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPasswordChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfilePhoto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("erp_Users", "AITStudent");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            BranchId = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 8, 4, 15, 53, 51, 483, DateTimeKind.Unspecified),
                            Email = "admin@erp.com",
                            FailedLoginAttempts = 0,
                            FullName = "Admin User",
                            IsActive = true,
                            IsEmailVerified = false,
                            IsLocked = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOkJcAU1YEZ50GcXjw9Sn+CYrXr+BWC75/EPUpfVliWCv4Alu/+3memoVLfE2G515w==",
                            RoleId = 1,
                            UserCode = "USR001",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("ERP_System.Models.User", b =>
                {
                    b.HasOne("ERP_System.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
